### ISSUE TITLE
Make the "check" status more distinct from "check outcome"

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#40]
Currently the "check" job's status looks very similar to the "check outcome" status. That is mostly due to the fact that they share the same name prefix: "PR Custom Review Status".

![image](https://user-images.githubusercontent.com/77391175/149779833-b3d7ed06-560c-4700-8f1a-7396ef38ccf6.png)

@TriplEight suggested that we further differentiate the custom status from the workflow status by their name. e.g.

1. ~Check reviewers~ Assign reviewers (https://github.com/paritytech/pr-custom-review/issues/40#issuecomment-1014577430)

2. ~Assign reviewers~ Check reviews (https://github.com/paritytech/pr-custom-review/issues/40#issuecomment-1014577430)

**Comment by TriplEight** [comment]
I've suggested that the first check (that's supposed to be green) is to be named something like `assign reviewers`, so it's clear why is it green. I know it also checks for the review statuses, hence the Error in the log, this has to be clarified after the error msg that the status is being passed by the following job and failed there.
The next job should be named smth like `check reviews` so it's clear why is it red.
Also, I think it makes sense to
- necessarily require the second job in branch protection rules in order to merge the PR
- only run the second job when there's a ready to merge label
But this may be out of the MVP scope.

**Comment by sergejparity** [comment]
Not sure how this can be achieved. As the names visible at screenshot above are derived from [`name` given in the action's config file](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name). Effectively we can change only the name of our own `manually` created status.
That is why I choose it to be the same with auto generated ( pull_request / pull_request_review ) statuses

**Comment by joao-paulo-parity** [comment]
> As the names visible at screenshot above are derived from name given in the action's config file

That's the point: we'll change the workflow name to match the suggestion

**Comment by sergejparity** [comment]
Probably I didn't get the idea. But this topic is about giving different names(prefixes) to `pull_request` and `pull_request_review` events generated workflows.
The only way I can see how to achieve that is to split current workflow into different ones - two independent workflow files in (.github/workflows) one for `pull_request` events and other `pull_request_review` events.  They may share the same config file and contribute to the same status check.
With that we can get the ability to name them differently.
With some drawbacks of course, we'll need to maintain two workflow files instead of one currently.

**Comment by joao-paulo-parity** [comment]
@sergejparity We want to differentiate the custom status' name from the workflow status' name, not differentate between the workflows' statuses (we don't care about them). The description was misleading before, sorry about that. I've made some changes to the text.

**Comment by sergejparity** [comment]
@joao-paulo-parity this makes sense.
There is no problem changing it. Even make it dynamic, depending on some conditions (but this will lead to over pollution with statuses)
